[project]
name = "pydanticai"
version = "0.1.0"
description = "Pydantic AI tutorial"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.3",
    "pydantic-ai>=1.9.1",
    "python-dotenv>=1.2.1",
]